<?php

namespace Tee\TeeworldsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
	public function getLastGame()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select("g");
		$qb->from("TeeworldsBundle:Game", "g");
		$qb->orderBy("g.date","DESC");
		$qb->setMaxResults(1);
		
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function getGameByHash( $hash )
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select("g");
		$qb->from("TeeworldsBundle:Game", "g");
		$qb->where("g.hash = :hash");
		$qb->setParameter("hash", $hash);
		
		return $qb->getQuery()->getResult();
	}
	
	public function getAllGame()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select("g");
		$qb->from("TeeworldsBundle:Game", "g");
		$qb->orderBy("g.date","DESC");
		
		return $qb->getQuery()->getResult();
	}
}
