<?php

namespace Tee\TeeworldsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends EntityRepository
{
	public function getWeaponByGame( $game )
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select("w");
		$qb->from("TeeworldsBundle:Weapon", "w");
		$qb->where( "w.game = :game ");
		$qb->setParameter( "game", $game);
		
		return $qb->getQuery()->getResult();
	}

	public function getTotalWeapon()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select("w.name as name, SUM( w.frag ) as kill ");
		$qb->from("TeeworldsBundle:Weapon", "w");
		$qb->groupBy( "w.name");
		$qb->orderBy( "kill", "DESC");
		
		return $qb->getQuery()->getResult( Query::HYDRATE_ARRAY );
	}
}
